// Package controlplane provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package controlplane

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"autoteam/internal/types"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ControlPlaneHealthResponseStatus.
const (
	ControlPlaneHealthResponseStatusDegraded  ControlPlaneHealthResponseStatus = "degraded"
	ControlPlaneHealthResponseStatusHealthy   ControlPlaneHealthResponseStatus = "healthy"
	ControlPlaneHealthResponseStatusUnhealthy ControlPlaneHealthResponseStatus = "unhealthy"
)

// Defines values for ControlPlaneHealthResponseWorkersHealth.
const (
	ControlPlaneHealthResponseWorkersHealthHealthy     ControlPlaneHealthResponseWorkersHealth = "healthy"
	ControlPlaneHealthResponseWorkersHealthUnhealthy   ControlPlaneHealthResponseWorkersHealth = "unhealthy"
	ControlPlaneHealthResponseWorkersHealthUnreachable ControlPlaneHealthResponseWorkersHealth = "unreachable"
)

// Defines values for RetryConfigBackoff.
const (
	Exponential RetryConfigBackoff = "exponential"
	Fixed       RetryConfigBackoff = "fixed"
	Linear      RetryConfigBackoff = "linear"
)

// Defines values for WorkerDetailsStatus.
const (
	Reachable   WorkerDetailsStatus = "reachable"
	Unknown     WorkerDetailsStatus = "unknown"
	Unreachable WorkerDetailsStatus = "unreachable"
)

// Defines values for GetWorkerLogsParamsRole.
const (
	Both      GetWorkerLogsParamsRole = "both"
	Collector GetWorkerLogsParamsRole = "collector"
	Executor  GetWorkerLogsParamsRole = "executor"
)

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	// Message Action result message
	Message string `json:"message"`

	// Timestamp Action timestamp
	Timestamp time.Time `json:"timestamp"`

	// WorkerId Worker ID that was acted upon
	WorkerId string `json:"worker_id"`
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse = types.ConfigResponse

// ControlPlaneHealthResponse defines model for ControlPlaneHealthResponse.
type ControlPlaneHealthResponse struct {
	// Message Additional health information
	Message *string `json:"message,omitempty"`

	// Status Overall control plane health status
	Status ControlPlaneHealthResponseStatus `json:"status"`

	// Timestamp Health check timestamp
	Timestamp time.Time `json:"timestamp"`

	// WorkersHealth Health status of each configured worker
	WorkersHealth map[string]ControlPlaneHealthResponseWorkersHealth `json:"workers_health"`
}

// ControlPlaneHealthResponseStatus Overall control plane health status
type ControlPlaneHealthResponseStatus string

// ControlPlaneHealthResponseWorkersHealth defines model for ControlPlaneHealthResponse.WorkersHealth.
type ControlPlaneHealthResponseWorkersHealth string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = types.ErrorResponse

// FlowInfo defines model for FlowInfo.
type FlowInfo = types.FlowInfo

// FlowResponse defines model for FlowResponse.
type FlowResponse = types.FlowResponse

// FlowStepInfo defines model for FlowStepInfo.
type FlowStepInfo = types.FlowStepInfo

// FlowStepsResponse defines model for FlowStepsResponse.
type FlowStepsResponse = types.FlowStepsResponse

// HealthCheck defines model for HealthCheck.
type HealthCheck = types.HealthCheck

// HealthResponse defines model for HealthResponse.
type HealthResponse = types.HealthResponse

// LogFile defines model for LogFile.
type LogFile = types.LogFile

// LogsResponse defines model for LogsResponse.
type LogsResponse = types.LogsResponse

// MetricsResponse defines model for MetricsResponse.
type MetricsResponse = types.MetricsResponse

// RetryConfig Configuration for retry behavior
type RetryConfig struct {
	// Backoff Backoff strategy for retry delays
	Backoff *RetryConfigBackoff `json:"backoff,omitempty"`

	// Delay Initial delay between retries in seconds
	Delay *int `json:"delay,omitempty"`

	// MaxAttempts Maximum number of retry attempts
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// MaxDelay Maximum delay between retries in seconds
	MaxDelay *int `json:"max_delay,omitempty"`
}

// RetryConfigBackoff Backoff strategy for retry delays
type RetryConfigBackoff string

// StatusResponse defines model for StatusResponse.
type StatusResponse = types.StatusResponse

// WorkerConfig Sanitized worker configuration
type WorkerConfig = types.WorkerConfig

// WorkerDetails defines model for WorkerDetails.
type WorkerDetails struct {
	// Id Worker ID from configuration
	Id string `json:"id"`

	// LastCheck Last health check timestamp
	LastCheck *time.Time `json:"last_check,omitempty"`

	// Status Worker connectivity status
	Status WorkerDetailsStatus `json:"status"`

	// Url Worker API URL
	Url        string      `json:"url"`
	WorkerInfo *WorkerInfo `json:"worker_info,omitempty"`
}

// WorkerDetailsStatus Worker connectivity status
type WorkerDetailsStatus string

// WorkerDetailsResponse defines model for WorkerDetailsResponse.
type WorkerDetailsResponse struct {
	// Timestamp Response timestamp
	Timestamp time.Time     `json:"timestamp"`
	Worker    WorkerDetails `json:"worker"`
}

// WorkerInfo defines model for WorkerInfo.
type WorkerInfo = types.WorkerInfo

// WorkerMetrics defines model for WorkerMetrics.
type WorkerMetrics = types.WorkerMetrics

// WorkersResponse defines model for WorkersResponse.
type WorkersResponse struct {
	// Timestamp Response timestamp
	Timestamp time.Time `json:"timestamp"`

	// Total Total number of configured workers
	Total   int             `json:"total"`
	Workers []WorkerDetails `json:"workers"`
}

// GetWorkerLogsParams defines parameters for GetWorkerLogs.
type GetWorkerLogsParams struct {
	// Role Filter logs by role (collector, executor, both)
	Role *GetWorkerLogsParamsRole `form:"role,omitempty" json:"role,omitempty"`

	// Limit Maximum number of log files to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWorkerLogsParamsRole defines parameters for GetWorkerLogs.
type GetWorkerLogsParamsRole string

// GetWorkerLogFileParams defines parameters for GetWorkerLogFile.
type GetWorkerLogFileParams struct {
	// Tail Number of last lines to return
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// API documentation
	// (GET /docs/)
	GetSwaggerUI(ctx echo.Context) error
	// Control plane health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// OpenAPI specification
	// (GET /openapi.yaml)
	GetOpenAPISpec(ctx echo.Context) error
	// List workers
	// (GET /workers)
	GetWorkers(ctx echo.Context) error
	// Get worker details
	// (GET /workers/{worker_id})
	GetWorker(ctx echo.Context, workerId string) error
	// Deploy worker
	// (POST /workers/{worker_id}/actions/deploy)
	DeployWorker(ctx echo.Context, workerId string) error
	// Pause worker
	// (POST /workers/{worker_id}/actions/pause)
	PauseWorker(ctx echo.Context, workerId string) error
	// Restart worker
	// (POST /workers/{worker_id}/actions/restart)
	RestartWorker(ctx echo.Context, workerId string) error
	// Stop worker
	// (POST /workers/{worker_id}/actions/stop)
	StopWorker(ctx echo.Context, workerId string) error
	// Unpause worker
	// (POST /workers/{worker_id}/actions/unpause)
	UnpauseWorker(ctx echo.Context, workerId string) error
	// Worker configuration
	// (GET /workers/{worker_id}/config)
	GetWorkerConfig(ctx echo.Context, workerId string) error
	// Worker flow configuration
	// (GET /workers/{worker_id}/flow)
	GetWorkerFlow(ctx echo.Context, workerId string) error
	// Worker flow steps
	// (GET /workers/{worker_id}/flow/steps)
	GetWorkerFlowSteps(ctx echo.Context, workerId string) error
	// Worker health check
	// (GET /workers/{worker_id}/health)
	GetWorkerHealth(ctx echo.Context, workerId string) error
	// Worker logs
	// (GET /workers/{worker_id}/logs)
	GetWorkerLogs(ctx echo.Context, workerId string, params GetWorkerLogsParams) error
	// Worker log file
	// (GET /workers/{worker_id}/logs/{filename})
	GetWorkerLogFile(ctx echo.Context, workerId string, filename string, params GetWorkerLogFileParams) error
	// Worker metrics
	// (GET /workers/{worker_id}/metrics)
	GetWorkerMetrics(ctx echo.Context, workerId string) error
	// Worker status
	// (GET /workers/{worker_id}/status)
	GetWorkerStatus(ctx echo.Context, workerId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwaggerUI converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwaggerUI(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwaggerUI(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetOpenAPISpec converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPISpec(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPISpec(ctx)
	return err
}

// GetWorkers converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkers(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkers(ctx)
	return err
}

// GetWorker converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorker(ctx, workerId)
	return err
}

// DeployWorker converts echo context to params.
func (w *ServerInterfaceWrapper) DeployWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployWorker(ctx, workerId)
	return err
}

// PauseWorker converts echo context to params.
func (w *ServerInterfaceWrapper) PauseWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PauseWorker(ctx, workerId)
	return err
}

// RestartWorker converts echo context to params.
func (w *ServerInterfaceWrapper) RestartWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestartWorker(ctx, workerId)
	return err
}

// StopWorker converts echo context to params.
func (w *ServerInterfaceWrapper) StopWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StopWorker(ctx, workerId)
	return err
}

// UnpauseWorker converts echo context to params.
func (w *ServerInterfaceWrapper) UnpauseWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnpauseWorker(ctx, workerId)
	return err
}

// GetWorkerConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerConfig(ctx, workerId)
	return err
}

// GetWorkerFlow converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerFlow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerFlow(ctx, workerId)
	return err
}

// GetWorkerFlowSteps converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerFlowSteps(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerFlowSteps(ctx, workerId)
	return err
}

// GetWorkerHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerHealth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerHealth(ctx, workerId)
	return err
}

// GetWorkerLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerLogsParams
	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameter("form", true, false, "role", ctx.QueryParams(), &params.Role)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerLogs(ctx, workerId, params)
	return err
}

// GetWorkerLogFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerLogFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", ctx.Param("filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filename: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerLogFileParams
	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameter("form", true, false, "tail", ctx.QueryParams(), &params.Tail)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tail: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerLogFile(ctx, workerId, filename, params)
	return err
}

// GetWorkerMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerMetrics(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerMetrics(ctx, workerId)
	return err
}

// GetWorkerStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerStatus(ctx, workerId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/", wrapper.GetSwaggerUI)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/openapi.yaml", wrapper.GetOpenAPISpec)
	router.GET(baseURL+"/workers", wrapper.GetWorkers)
	router.GET(baseURL+"/workers/:worker_id", wrapper.GetWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/deploy", wrapper.DeployWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/pause", wrapper.PauseWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/restart", wrapper.RestartWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/stop", wrapper.StopWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/unpause", wrapper.UnpauseWorker)
	router.GET(baseURL+"/workers/:worker_id/config", wrapper.GetWorkerConfig)
	router.GET(baseURL+"/workers/:worker_id/flow", wrapper.GetWorkerFlow)
	router.GET(baseURL+"/workers/:worker_id/flow/steps", wrapper.GetWorkerFlowSteps)
	router.GET(baseURL+"/workers/:worker_id/health", wrapper.GetWorkerHealth)
	router.GET(baseURL+"/workers/:worker_id/logs", wrapper.GetWorkerLogs)
	router.GET(baseURL+"/workers/:worker_id/logs/:filename", wrapper.GetWorkerLogFile)
	router.GET(baseURL+"/workers/:worker_id/metrics", wrapper.GetWorkerMetrics)
	router.GET(baseURL+"/workers/:worker_id/status", wrapper.GetWorkerStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce28bt7L/KsTeArfFlSylL6AC7h9u+jLqnBpxghycxMegdkcrNlxyS3Jlq4G/+wFf",
	"++RqV1Lj+jj+K86SHA5nfsMZDjn6EMU8yzkDpmS0+BDJeA0ZNn+exopw9hJkzpkE/SUXPAehCJj2DKTE",
	"qWlIQMaC5Lp/tHADkQBZUIV8t0mktjlEi0gqQVga3U0iRTKQCmd5L42qxyRacZFhFS2iBCuY6pYQzRsu",
	"3oO4JkmX5hvThM5+QGqNFbrBEuFYQYKKnLMurbtJJOCPgghIosXbqFpHNUV9CVclAb78HWKlmXnO2Yqk",
	"/SKMTbv+6zMBq2gR/c+sUsfM6WJm+ba0BsTmp9pbcK3FOsZ2rm8S3U5TPnUf9T/ypLXgWpcpyXIulJEB",
	"VutoEeFCcQU4mxGmQDBMZ4aG4eU5Z0pwekExg18AU7U+BIdJQvSfmKK1oYEIs7IgIX1PIqmwKmSX0G8b",
	"EJhSFFuuUK7Z8jTdoEkErMi07Oz3bTSJEkgFTkDjpGD+89V+hmBXj+I1xO8PNgd5bWfX5HEplYuGGLvs",
	"VzzrvwXgeI2XFIIrCDJtRYP4CumxyIKqEJAgy1bUMZkWDEvZ1hfeWlLI7n4UgotdZpcE4GIGIdMWWCDo",
	"1r5Bh+1xduyRlmr52ttQmxI62E5/ovzmjK14V8bANFaSa6kgD5jUP4psCcJAw3ac4ViRDSDbv1yCnjMF",
	"YTRwC3Ghh1/HvGCqS/MVV5giVlJeUX6DylFhohRLdV32CdD0YtUEdecW1dGGKIs4BimvBVYB7F3aVqRb",
	"w6yXs6wox6qawS7XIE0vv0/ebdmYbogwpNZgZgtIp4W0Ov1JS7+jMFeC5Si49Zu1WcaALy15uB8/6iW7",
	"n3E2lnmUsC4V5GH7tOYWCJLWoNYgDC60bhGRKC6EAKbo1kOSpdXKl5xTwEwLFIs0AL3TFJiayhxisiIx",
	"wiItMhNuTiKiIDMjutum/YCFwFvrX3JgCbB4e51zSuJtd54L8x2tuEBrzBJKWIqqYWiFCS0E1D21/nS9",
	"wlJrAVN67WzU/U+jh4LSGsBsWzaGvZ+eRl6HdpBzIpW3OMRwBhKpNZH2/24gMhvJeGk44xunPd85pDFg",
	"m10xwYCb/5FtiOBMaxNtsCB6HmkU4OePAs55cB+vfIOxm5q41liiJQBzOKwvqranE5YXAbJn+jPKBc9y",
	"1cNktVDrF3b5/JXgmfUIdWfQQ2gfB7O/bzFz8EIFl/2b+b4XuwKU2F6b2Ubwa3ojrBRkuRrNs7aELvXX",
	"jPxRQGUrwZFwuweLujfSu39SUEgss6OZHJCpEpjJ8kSBtAAoVkFKdt4B5/RSd6rOeXaNXrAdJp7bXbkp",
	"f/T5HP0/WhEhNXvbL4IGIt+T/PpmDQE4Xr4nuQ7U7X6wc0k+ohm0YtdxVdChaMyGGHpBbgMKBTGN9UqU",
	"4XrAXidmvgS9ETJtQ867DsDRfrv0uEf7bdkf6ZRBXukyhmKekq2AN/kYcZDT5cggvS/o7xwHXTdD+qCw",
	"qinYg3VkD7jP9aF8j4RE4yy/48zYl4dojLfptVo0k2MTuuigJhCkhE/Wo+RWX+yREuuHNNZ2OS4T5nFs",
	"5CB3xS+7aNVX1YlszlhCNiQpqtRRXegyFNYMJY+G00V/T45oTMrFKmcPsBxvYec8/YnQ0CmPUAgHD+c8",
	"Rbq1N3LIeEJWJBQ3n+tAxjcfsNkJTqE34awbEZaSxwQrSNANUWtEeVoDQcwphViZTI71kebPJW8kuGo7",
	"BPkzMJ8WGNJN+mC/3CpoJA4IU99+PbzJlvJ1s9TENgoAXnHHaH6H66M8He/5PC8PzelRh9QRPs+s92CX",
	"15DlwRp5oQOyWO5KwZsO47ZvR+2eMjCetb1F1170wdKrR/XdIN7lxO0JQp9KbXi7hDXeELMJNEW9xPF7",
	"vlpZSiusQ4BFtCK35izcpP297YqkElhBuq2RT4DibSMV4ijArVUaMWijhAEWPSkPircNLuZdJ0o0HTsZ",
	"WoK60Ud3F93rLUqCPmloNjJ8SzLNyVfz+STKCLP/m4fi+gzf+kORbDDwrM3AC0u1ZnjNs0N94mf1eZ/1",
	"zdtdtWE4PO1e6/52PsDAXSDmuDTO+i8NqrLg3Yg/a2ri2N2pZfamxCOo31f1BEYhmp3oiCTGlYiCMZt1",
	"tDmZPQMkK6cD9vMiD6cYnGe3zShx9js+uHKyOzDGaqn94J2pcbHcFRrW9vtneVtX3t/5tQYvfHpl5dr9",
	"pSCWyAkpIHZ9KBy+OaqOjrWrxWAqIBwvOsb6okUttevwyFeAMzPO5RGJ7NxotpO3PZOHExGTaANCBvOF",
	"bpxvDyFuGEANxR8Jnx9AYUJld/PZ/QTD5CPbiAqnI2N/zA7E7Ovjrsf79qY3JeIZxIpsiNp296bqRrx5",
	"P67/957xGxbcpgpBe+c7vThDr1+e73rX4i5zxm7orQ3IvFnRHEx6MwBtxfZ7l48TQjtDGrVGj732Mitj",
	"3Pk8pyaoruvcYEKNOvuU5XoQ2gBH947lsM3nvjeNvsRnRfVq/M5yXAK0eUwIaCatLlR6rgBONyBwCq17",
	"dLTzAgU7Qx9z51H2PTaQsOnoMXHEWNm/KA88R4n/3u1+5NG584gofJPg28ZmClr7STtfENxfRp7L9WAJ",
	"cSGI2l7q6awUT3PyK2xPC/sqq5UzzF08rB3Ce7AnN1yotT6ZxR4jRHddA07MVme3meif09OLs+mvsK3E",
	"gs1M0d2duRu1m13MmcKxgYQbeFooruMa5yAW0VqpXC5ms5SodbE8iXk22/JCTLlIZxo/Uw2gwNuvV68u",
	"DN+a5wwznBKWIswSlHFGFNf6RllBFckpID+rV+bJO/aOvdIBlSaBY2UiRYxiYEpgiriI12AOtCbwwuZC",
	"91afq7R+QCqJFEekSt/elJ5V0z6lFAFLck6YpiwACcDJlDO6nWhKG5IY9ipONeMuZK29HkR6xMk7Zs7I",
	"MTgzcZJ8cfaqI0SeA5O8EDGcaPm5QXKm+5qzi6J1JSD3ABKZF5Ca+9pGvIiencxP5uaCMgeGcxItoq9O",
	"5idf6aAcq7XB1yzhsZzpv1IIXM9d3uA0BYFeW0WZfcA9wdKST3hsXml4rJWHtLMkWkQ/g3LjX2vGhLN6",
	"M++X87kHmDt8KrhVs7XKaPXAOPC44K6DpBqLv7x6cY5ynIK1piLLsNhqeQVYVTiV2kj1+qMr3X9WvX4M",
	"yuIlqEIwaR4ErNtPF/XH5sNPDQmcpgJSm861CHNzBET1i28ZkBPOc+qse/a7tH68Eteu3WvHc9mAXJ/v",
	"eMZ6N4m++QsZaz4zDPBy5vwPkiA2+pRojvdNJQf5jd11lNe2fw1q9O3M4mSLLegGtf5bDkxjyb9SqtJx",
	"yu1FIcW6UZc5xPtp93bqOdvDHII8tkQV7hO0iZqH3Cke6t4vuQfQLedrjEGtgYgqBO7I6U3pLj+aBbSD",
	"loD8/EMsv/CHCHXDYy26cGrzXxqam30oCxHuBrWY2MgG4SUvFMIlQKq8RY/WjEsROANlwPK290TvAxIT",
	"YZbhSL1WooqglChgsgP7Vx8dKe3DbUBfbmVJFRN+Pf/6/uDiD4hcoRUvWPIg8fozeLiWctoDtebNN2dy",
	"lkBOuTl45VwGUPyDae/C1jhmTFgAwHbII8VwqzRrF3i1FCCpvcGiWwvle0TS9zjx4Tn6HE7Sk0mpP8w0",
	"wJdQcvrFk6GFDM1ZQJXYcjbmLGiEjeW4cIf5oIld6Oa9LMyM+NQNzEg1ZF5PAG4C2OLrCPwKkAq7JFYQ",
	"wS9th70w7MZ86ih2sn0C8ggge5gdAWWpeN6P40vF871ArAd86gjWIs2f8DsCvwZeR4C3YAORxGvbYS8I",
	"uzGfOoqdbJ9gPAxjj7IDkFz96kIwZXIh+O0WKe5I/69/XVJeHPQnS8oXFY8Lv61fdeiHTPM9x8PA7Zf3",
	"zkD9LUgTtG/CD6k8dHONvB3A9QXOI2FrL78HQfuTrVF+XJBtlFD3q8qI6Am1o1AbkNV+0J2VL/r2AbB9",
	"4DcOxpeuQOzxYblZtzYAaCvnJyDvAnJZSzgSwANXyF3wunvKYeCW18OPC7XD99Bv6hfntQvop2BXPFjb",
	"6bl9H7IeX7U10nZ09xGWc25ro+7fbiaByjsFwvK93NqKv8/Lor4J8jV9E7Tkav2F5+WPAsyvEThmTBVh",
	"fd7DygO77HULYcoKNC13YS6Je5iiJCOqwVVZ+/LNvFFAM1TA8jF3m0ahWz++DQ6fHGOPcftawz2MevbB",
	"14ve7WfftlJ3lI27ctIHYOa+wtg9kA5MVGvtnyfHSu/50SL691s8/fN0+q/59Lvrk+nV/717d0J5+lk0",
	"wqarOhjzIpkSNsKYFSa0Yct18/0LDNg89cspJmzPx01l7bYn9jcZKRcVOP8rDNawuofR1kp1RxqrGzHC",
	"Vqun548rlG2XAvdrLKtqm59cTAixtXLskYCtSrRG4tU93R2G66V/sPi40NqqDt11Z/aATlwPEKtVTVcb",
	"qrWKDoOYei3H26u7yQetYHueC0HqnMe4/WvCtnejbmAxm1Hdc82lWnw3/24eabKOmR6YmoILML/Ih1mC",
	"EiJjvgGxraoe2tDVANj5gzKBkS4Z0h14YYoxklrVRWi4lWN3tPdqZAXxNqaA7F1OiIS/5bm7uvtPAAAA",
	"//+F3lNSw1wAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
