// Package controlplane provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package controlplane

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"autoteam/internal/types"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ControlPlaneHealthResponseStatus.
const (
	ControlPlaneHealthResponseStatusDegraded  ControlPlaneHealthResponseStatus = "degraded"
	ControlPlaneHealthResponseStatusHealthy   ControlPlaneHealthResponseStatus = "healthy"
	ControlPlaneHealthResponseStatusUnhealthy ControlPlaneHealthResponseStatus = "unhealthy"
)

// Defines values for ControlPlaneHealthResponseWorkersHealth.
const (
	ControlPlaneHealthResponseWorkersHealthHealthy     ControlPlaneHealthResponseWorkersHealth = "healthy"
	ControlPlaneHealthResponseWorkersHealthUnhealthy   ControlPlaneHealthResponseWorkersHealth = "unhealthy"
	ControlPlaneHealthResponseWorkersHealthUnreachable ControlPlaneHealthResponseWorkersHealth = "unreachable"
)

// Defines values for FlowStepInputDependencyPolicy.
const (
	FlowStepInputDependencyPolicyAllComplete FlowStepInputDependencyPolicy = "all_complete"
	FlowStepInputDependencyPolicyAllSuccess  FlowStepInputDependencyPolicy = "all_success"
	FlowStepInputDependencyPolicyAnySuccess  FlowStepInputDependencyPolicy = "any_success"
	FlowStepInputDependencyPolicyFailFast    FlowStepInputDependencyPolicy = "fail_fast"
)

// Defines values for FlowStepOutputDependencyPolicy.
const (
	FlowStepOutputDependencyPolicyAllComplete FlowStepOutputDependencyPolicy = "all_complete"
	FlowStepOutputDependencyPolicyAllSuccess  FlowStepOutputDependencyPolicy = "all_success"
	FlowStepOutputDependencyPolicyAnySuccess  FlowStepOutputDependencyPolicy = "any_success"
	FlowStepOutputDependencyPolicyFailFast    FlowStepOutputDependencyPolicy = "fail_fast"
)

// Defines values for RetryConfigBackoff.
const (
	Exponential RetryConfigBackoff = "exponential"
	Fixed       RetryConfigBackoff = "fixed"
	Linear      RetryConfigBackoff = "linear"
)

// Defines values for WorkerDetailsStatus.
const (
	Reachable   WorkerDetailsStatus = "reachable"
	Unknown     WorkerDetailsStatus = "unknown"
	Unreachable WorkerDetailsStatus = "unreachable"
)

// Defines values for GetWorkerRuntimeLogsParamsRole.
const (
	Both      GetWorkerRuntimeLogsParamsRole = "both"
	Collector GetWorkerRuntimeLogsParamsRole = "collector"
	Executor  GetWorkerRuntimeLogsParamsRole = "executor"
)

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	// Message Action result message
	Message string `json:"message"`

	// Timestamp Action timestamp
	Timestamp time.Time `json:"timestamp"`

	// WorkerId Worker ID that was acted upon
	WorkerId string `json:"worker_id"`
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse = types.ConfigResponse

// ControlPlaneHealthResponse defines model for ControlPlaneHealthResponse.
type ControlPlaneHealthResponse struct {
	// Message Additional health information
	Message *string `json:"message,omitempty"`

	// Status Overall control plane health status
	Status ControlPlaneHealthResponseStatus `json:"status"`

	// Timestamp Health check timestamp
	Timestamp time.Time `json:"timestamp"`

	// WorkersHealth Health status of each configured worker
	WorkersHealth map[string]ControlPlaneHealthResponseWorkersHealth `json:"workers_health"`
}

// ControlPlaneHealthResponseStatus Overall control plane health status
type ControlPlaneHealthResponseStatus string

// ControlPlaneHealthResponseWorkersHealth defines model for ControlPlaneHealthResponse.WorkersHealth.
type ControlPlaneHealthResponseWorkersHealth string

// CreateWorkerRequest defines model for CreateWorkerRequest.
type CreateWorkerRequest struct {
	// Enabled Whether the worker is enabled
	Enabled *bool `json:"enabled,omitempty"`

	// Name Worker name (must be unique)
	Name string `json:"name"`

	// Prompt Worker-specific prompt
	Prompt   string               `json:"prompt"`
	Settings *WorkerSettingsInput `json:"settings,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = types.ErrorResponse

// FlowInfo defines model for FlowInfo.
type FlowInfo = types.FlowInfo

// FlowResponse defines model for FlowResponse.
type FlowResponse = types.FlowResponse

// FlowStepInfo defines model for FlowStepInfo.
type FlowStepInfo = types.FlowStepInfo

// FlowStepInput defines model for FlowStepInput.
type FlowStepInput struct {
	// Args Agent-specific arguments
	Args *[]string `json:"args,omitempty"`

	// DependencyPolicy Policy for handling dependency failures
	DependencyPolicy *FlowStepInputDependencyPolicy `json:"dependency_policy,omitempty"`

	// DependsOn List of step names this step depends on
	DependsOn *[]string `json:"depends_on,omitempty"`

	// Env Environment variables for the step
	Env *map[string]string `json:"env,omitempty"`

	// Input Input prompt for the step
	Input *string `json:"input,omitempty"`

	// Name Unique step name
	Name string `json:"name"`

	// Output Output transformation template
	Output *string `json:"output,omitempty"`

	// Retry Configuration for retry behavior
	Retry *RetryConfig `json:"retry,omitempty"`

	// SkipWhen Skip condition template
	SkipWhen *string `json:"skip_when,omitempty"`

	// Type Agent type
	Type string `json:"type"`
}

// FlowStepInputDependencyPolicy Policy for handling dependency failures
type FlowStepInputDependencyPolicy string

// FlowStepOutput defines model for FlowStepOutput.
type FlowStepOutput struct {
	// Args Agent-specific arguments
	Args *[]string `json:"args,omitempty"`

	// CreatedAt Step creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// DependencyPolicy Policy for handling dependency failures
	DependencyPolicy *FlowStepOutputDependencyPolicy `json:"dependency_policy,omitempty"`

	// DependsOn List of step names this step depends on
	DependsOn *[]string `json:"depends_on,omitempty"`

	// Env Environment variables for the step
	Env *map[string]string `json:"env,omitempty"`

	// Id Step UUID
	Id openapi_types.UUID `json:"id"`

	// Input Input prompt for the step
	Input *string `json:"input,omitempty"`

	// Name Unique step name
	Name string `json:"name"`

	// Order Execution order within worker
	Order int `json:"order"`

	// Output Output transformation template
	Output *string `json:"output,omitempty"`

	// Retry Configuration for retry behavior
	Retry *RetryConfig `json:"retry,omitempty"`

	// SkipWhen Skip condition template
	SkipWhen *string `json:"skip_when,omitempty"`

	// Type Agent type
	Type string `json:"type"`

	// UpdatedAt Step last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// WorkerId Worker UUID
	WorkerId openapi_types.UUID `json:"worker_id"`
}

// FlowStepOutputDependencyPolicy Policy for handling dependency failures
type FlowStepOutputDependencyPolicy string

// FlowStepsResponse defines model for FlowStepsResponse.
type FlowStepsResponse = types.FlowStepsResponse

// HealthCheck defines model for HealthCheck.
type HealthCheck = types.HealthCheck

// HealthResponse defines model for HealthResponse.
type HealthResponse = types.HealthResponse

// LogFile defines model for LogFile.
type LogFile = types.LogFile

// LogsResponse defines model for LogsResponse.
type LogsResponse = types.LogsResponse

// MCPServerConfig defines model for MCPServerConfig.
type MCPServerConfig struct {
	// Args Command arguments
	Args *[]string `json:"args,omitempty"`

	// Command Command to run the MCP server
	Command string `json:"command"`

	// Env Environment variables
	Env *map[string]string `json:"env,omitempty"`
}

// MetricsResponse defines model for MetricsResponse.
type MetricsResponse = types.MetricsResponse

// RetryConfig Configuration for retry behavior
type RetryConfig struct {
	// Backoff Backoff strategy for retry delays
	Backoff *RetryConfigBackoff `json:"backoff,omitempty"`

	// Delay Initial delay between retries in seconds
	Delay *int `json:"delay,omitempty"`

	// MaxAttempts Maximum number of retry attempts
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// MaxDelay Maximum delay between retries in seconds
	MaxDelay *int `json:"max_delay,omitempty"`
}

// RetryConfigBackoff Backoff strategy for retry delays
type RetryConfigBackoff string

// StatusResponse defines model for StatusResponse.
type StatusResponse = types.StatusResponse

// UpdateWorkerRequest defines model for UpdateWorkerRequest.
type UpdateWorkerRequest struct {
	// Enabled Whether the worker is enabled
	Enabled *bool `json:"enabled,omitempty"`

	// Name Worker name (must be unique)
	Name *string `json:"name,omitempty"`

	// Prompt Worker-specific prompt
	Prompt   *string              `json:"prompt,omitempty"`
	Settings *WorkerSettingsInput `json:"settings,omitempty"`
}

// UpdateWorkerSettingsRequest defines model for UpdateWorkerSettingsRequest.
type UpdateWorkerSettingsRequest struct {
	// CommonPrompt Common prompt shared across all steps
	CommonPrompt *string `json:"common_prompt,omitempty"`

	// Debug Enable debug mode
	Debug *bool `json:"debug,omitempty"`

	// Flow Flow steps configuration
	Flow *[]FlowStepInput `json:"flow,omitempty"`

	// InstallDeps Whether to install dependencies
	InstallDeps *bool `json:"install_deps,omitempty"`

	// MaxAttempts Maximum retry attempts for failed operations
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// McpServers Model Context Protocol server configurations
	McpServers *map[string]MCPServerConfig `json:"mcp_servers,omitempty"`

	// Meta Metadata and additional configuration
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// Service Service configuration options
	Service *map[string]interface{} `json:"service,omitempty"`

	// SleepDuration Sleep duration between flow executions in seconds
	SleepDuration *int `json:"sleep_duration,omitempty"`

	// TeamName Team name for this worker
	TeamName *string `json:"team_name,omitempty"`
}

// WorkerConfig Sanitized worker configuration
type WorkerConfig = types.WorkerConfig

// WorkerDetails defines model for WorkerDetails.
type WorkerDetails struct {
	// Id Worker ID from configuration
	Id string `json:"id"`

	// LastCheck Last health check timestamp
	LastCheck *time.Time `json:"last_check,omitempty"`

	// Status Worker connectivity status
	Status WorkerDetailsStatus `json:"status"`

	// Url Worker API URL
	Url        string      `json:"url"`
	WorkerInfo *WorkerInfo `json:"worker_info,omitempty"`
}

// WorkerDetailsStatus Worker connectivity status
type WorkerDetailsStatus string

// WorkerDetailsResponse defines model for WorkerDetailsResponse.
type WorkerDetailsResponse struct {
	// Timestamp Response timestamp
	Timestamp time.Time     `json:"timestamp"`
	Worker    WorkerDetails `json:"worker"`
}

// WorkerInfo defines model for WorkerInfo.
type WorkerInfo = types.WorkerInfo

// WorkerMetrics defines model for WorkerMetrics.
type WorkerMetrics = types.WorkerMetrics

// WorkerResponse defines model for WorkerResponse.
type WorkerResponse struct {
	// CreatedAt Worker creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Enabled Whether the worker is enabled
	Enabled bool `json:"enabled"`

	// Id Worker UUID
	Id openapi_types.UUID `json:"id"`

	// Name Worker name
	Name string `json:"name"`

	// Prompt Worker-specific prompt
	Prompt   string                `json:"prompt"`
	Settings *WorkerSettingsOutput `json:"settings,omitempty"`

	// UpdatedAt Worker last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// WorkerSettingsInput defines model for WorkerSettingsInput.
type WorkerSettingsInput struct {
	// CommonPrompt Common prompt shared across all steps
	CommonPrompt *string `json:"common_prompt,omitempty"`

	// Debug Enable debug mode
	Debug *bool `json:"debug,omitempty"`

	// Flow Flow steps configuration
	Flow *[]FlowStepInput `json:"flow,omitempty"`

	// InstallDeps Whether to install dependencies
	InstallDeps *bool `json:"install_deps,omitempty"`

	// MaxAttempts Maximum retry attempts for failed operations
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// McpServers Model Context Protocol server configurations
	McpServers *map[string]MCPServerConfig `json:"mcp_servers,omitempty"`

	// Meta Metadata and additional configuration
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// Service Service configuration options
	Service *map[string]interface{} `json:"service,omitempty"`

	// SleepDuration Sleep duration between flow executions in seconds
	SleepDuration *int `json:"sleep_duration,omitempty"`

	// TeamName Team name for this worker
	TeamName *string `json:"team_name,omitempty"`
}

// WorkerSettingsOutput defines model for WorkerSettingsOutput.
type WorkerSettingsOutput struct {
	// CommonPrompt Common prompt shared across all steps
	CommonPrompt *string `json:"common_prompt,omitempty"`

	// CreatedAt Settings creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Debug Enable debug mode
	Debug *bool `json:"debug,omitempty"`

	// Flow Flow steps configuration
	Flow *[]FlowStepOutput `json:"flow,omitempty"`

	// Id Settings UUID
	Id openapi_types.UUID `json:"id"`

	// InstallDeps Whether to install dependencies
	InstallDeps *bool `json:"install_deps,omitempty"`

	// MaxAttempts Maximum retry attempts for failed operations
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// McpServers Model Context Protocol server configurations
	McpServers *map[string]MCPServerConfig `json:"mcp_servers,omitempty"`

	// Meta Metadata and additional configuration
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// Service Service configuration options
	Service *map[string]interface{} `json:"service,omitempty"`

	// SleepDuration Sleep duration between flow executions in seconds
	SleepDuration int `json:"sleep_duration"`

	// TeamName Team name for this worker
	TeamName string `json:"team_name"`

	// UpdatedAt Settings last update timestamp
	UpdatedAt time.Time `json:"updated_at"`

	// WorkerId Worker UUID
	WorkerId openapi_types.UUID `json:"worker_id"`
}

// WorkerSettingsResponse defines model for WorkerSettingsResponse.
type WorkerSettingsResponse struct {
	Settings WorkerSettingsOutput `json:"settings"`

	// Timestamp Response timestamp
	Timestamp time.Time `json:"timestamp"`
}

// WorkersResponse defines model for WorkersResponse.
type WorkersResponse struct {
	// Timestamp Response timestamp
	Timestamp time.Time `json:"timestamp"`

	// Total Total number of configured workers
	Total   int              `json:"total"`
	Workers []WorkerResponse `json:"workers"`
}

// GetWorkerRuntimeLogsParams defines parameters for GetWorkerRuntimeLogs.
type GetWorkerRuntimeLogsParams struct {
	// Role Filter logs by role (collector, executor, both)
	Role *GetWorkerRuntimeLogsParamsRole `form:"role,omitempty" json:"role,omitempty"`

	// Limit Maximum number of log files to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWorkerRuntimeLogsParamsRole defines parameters for GetWorkerRuntimeLogs.
type GetWorkerRuntimeLogsParamsRole string

// GetWorkerRuntimeLogFileParams defines parameters for GetWorkerRuntimeLogFile.
type GetWorkerRuntimeLogFileParams struct {
	// Tail Number of last lines to return
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`
}

// CreateWorkerJSONRequestBody defines body for CreateWorker for application/json ContentType.
type CreateWorkerJSONRequestBody = CreateWorkerRequest

// UpdateWorkerJSONRequestBody defines body for UpdateWorker for application/json ContentType.
type UpdateWorkerJSONRequestBody = UpdateWorkerRequest

// UpdateWorkerSettingsJSONRequestBody defines body for UpdateWorkerSettings for application/json ContentType.
type UpdateWorkerSettingsJSONRequestBody = UpdateWorkerSettingsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// API documentation
	// (GET /docs/)
	GetSwaggerUI(ctx echo.Context) error
	// Control plane health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// OpenAPI specification
	// (GET /openapi.yaml)
	GetOpenAPISpec(ctx echo.Context) error
	// List workers
	// (GET /workers)
	GetWorkers(ctx echo.Context) error
	// Create worker
	// (POST /workers)
	CreateWorker(ctx echo.Context) error
	// Delete worker
	// (DELETE /workers/{worker_id})
	DeleteWorker(ctx echo.Context, workerId string) error
	// Get worker details
	// (GET /workers/{worker_id})
	GetWorker(ctx echo.Context, workerId string) error
	// Update worker
	// (PUT /workers/{worker_id})
	UpdateWorker(ctx echo.Context, workerId string) error
	// Deploy worker
	// (POST /workers/{worker_id}/actions/deploy)
	DeployWorker(ctx echo.Context, workerId string) error
	// Pause worker
	// (POST /workers/{worker_id}/actions/pause)
	PauseWorker(ctx echo.Context, workerId string) error
	// Restart worker
	// (POST /workers/{worker_id}/actions/restart)
	RestartWorker(ctx echo.Context, workerId string) error
	// Stop worker
	// (POST /workers/{worker_id}/actions/stop)
	StopWorker(ctx echo.Context, workerId string) error
	// Unpause worker
	// (POST /workers/{worker_id}/actions/unpause)
	UnpauseWorker(ctx echo.Context, workerId string) error
	// Get worker runtime info
	// (GET /workers/{worker_id}/runtime)
	GetWorkerRuntime(ctx echo.Context, workerId string) error
	// Worker runtime configuration
	// (GET /workers/{worker_id}/runtime/config)
	GetWorkerRuntimeConfig(ctx echo.Context, workerId string) error
	// Worker runtime flow execution state
	// (GET /workers/{worker_id}/runtime/flow)
	GetWorkerRuntimeFlow(ctx echo.Context, workerId string) error
	// Worker runtime flow steps
	// (GET /workers/{worker_id}/runtime/flow/steps)
	GetWorkerRuntimeFlowSteps(ctx echo.Context, workerId string) error
	// Worker runtime health check
	// (GET /workers/{worker_id}/runtime/health)
	GetWorkerRuntimeHealth(ctx echo.Context, workerId string) error
	// Worker runtime logs
	// (GET /workers/{worker_id}/runtime/logs)
	GetWorkerRuntimeLogs(ctx echo.Context, workerId string, params GetWorkerRuntimeLogsParams) error
	// Worker runtime log file
	// (GET /workers/{worker_id}/runtime/logs/{filename})
	GetWorkerRuntimeLogFile(ctx echo.Context, workerId string, filename string, params GetWorkerRuntimeLogFileParams) error
	// Worker runtime metrics
	// (GET /workers/{worker_id}/runtime/metrics)
	GetWorkerRuntimeMetrics(ctx echo.Context, workerId string) error
	// Worker runtime status
	// (GET /workers/{worker_id}/runtime/status)
	GetWorkerRuntimeStatus(ctx echo.Context, workerId string) error
	// Get worker settings
	// (GET /workers/{worker_id}/settings)
	GetWorkerSettings(ctx echo.Context, workerId string) error
	// Update worker settings
	// (PUT /workers/{worker_id}/settings)
	UpdateWorkerSettings(ctx echo.Context, workerId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwaggerUI converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwaggerUI(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwaggerUI(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetOpenAPISpec converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPISpec(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPISpec(ctx)
	return err
}

// GetWorkers converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkers(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkers(ctx)
	return err
}

// CreateWorker converts echo context to params.
func (w *ServerInterfaceWrapper) CreateWorker(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateWorker(ctx)
	return err
}

// DeleteWorker converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteWorker(ctx, workerId)
	return err
}

// GetWorker converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorker(ctx, workerId)
	return err
}

// UpdateWorker converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateWorker(ctx, workerId)
	return err
}

// DeployWorker converts echo context to params.
func (w *ServerInterfaceWrapper) DeployWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployWorker(ctx, workerId)
	return err
}

// PauseWorker converts echo context to params.
func (w *ServerInterfaceWrapper) PauseWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PauseWorker(ctx, workerId)
	return err
}

// RestartWorker converts echo context to params.
func (w *ServerInterfaceWrapper) RestartWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestartWorker(ctx, workerId)
	return err
}

// StopWorker converts echo context to params.
func (w *ServerInterfaceWrapper) StopWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StopWorker(ctx, workerId)
	return err
}

// UnpauseWorker converts echo context to params.
func (w *ServerInterfaceWrapper) UnpauseWorker(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnpauseWorker(ctx, workerId)
	return err
}

// GetWorkerRuntime converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntime(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntime(ctx, workerId)
	return err
}

// GetWorkerRuntimeConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeConfig(ctx, workerId)
	return err
}

// GetWorkerRuntimeFlow converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeFlow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeFlow(ctx, workerId)
	return err
}

// GetWorkerRuntimeFlowSteps converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeFlowSteps(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeFlowSteps(ctx, workerId)
	return err
}

// GetWorkerRuntimeHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeHealth(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeHealth(ctx, workerId)
	return err
}

// GetWorkerRuntimeLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerRuntimeLogsParams
	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameter("form", true, false, "role", ctx.QueryParams(), &params.Role)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeLogs(ctx, workerId, params)
	return err
}

// GetWorkerRuntimeLogFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeLogFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", ctx.Param("filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filename: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkerRuntimeLogFileParams
	// ------------- Optional query parameter "tail" -------------

	err = runtime.BindQueryParameter("form", true, false, "tail", ctx.QueryParams(), &params.Tail)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tail: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeLogFile(ctx, workerId, filename, params)
	return err
}

// GetWorkerRuntimeMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeMetrics(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeMetrics(ctx, workerId)
	return err
}

// GetWorkerRuntimeStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerRuntimeStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerRuntimeStatus(ctx, workerId)
	return err
}

// GetWorkerSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerSettings(ctx, workerId)
	return err
}

// UpdateWorkerSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateWorkerSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "worker_id" -------------
	var workerId string

	err = runtime.BindStyledParameterWithOptions("simple", "worker_id", ctx.Param("worker_id"), &workerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter worker_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateWorkerSettings(ctx, workerId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/", wrapper.GetSwaggerUI)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/openapi.yaml", wrapper.GetOpenAPISpec)
	router.GET(baseURL+"/workers", wrapper.GetWorkers)
	router.POST(baseURL+"/workers", wrapper.CreateWorker)
	router.DELETE(baseURL+"/workers/:worker_id", wrapper.DeleteWorker)
	router.GET(baseURL+"/workers/:worker_id", wrapper.GetWorker)
	router.PUT(baseURL+"/workers/:worker_id", wrapper.UpdateWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/deploy", wrapper.DeployWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/pause", wrapper.PauseWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/restart", wrapper.RestartWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/stop", wrapper.StopWorker)
	router.POST(baseURL+"/workers/:worker_id/actions/unpause", wrapper.UnpauseWorker)
	router.GET(baseURL+"/workers/:worker_id/runtime", wrapper.GetWorkerRuntime)
	router.GET(baseURL+"/workers/:worker_id/runtime/config", wrapper.GetWorkerRuntimeConfig)
	router.GET(baseURL+"/workers/:worker_id/runtime/flow", wrapper.GetWorkerRuntimeFlow)
	router.GET(baseURL+"/workers/:worker_id/runtime/flow/steps", wrapper.GetWorkerRuntimeFlowSteps)
	router.GET(baseURL+"/workers/:worker_id/runtime/health", wrapper.GetWorkerRuntimeHealth)
	router.GET(baseURL+"/workers/:worker_id/runtime/logs", wrapper.GetWorkerRuntimeLogs)
	router.GET(baseURL+"/workers/:worker_id/runtime/logs/:filename", wrapper.GetWorkerRuntimeLogFile)
	router.GET(baseURL+"/workers/:worker_id/runtime/metrics", wrapper.GetWorkerRuntimeMetrics)
	router.GET(baseURL+"/workers/:worker_id/runtime/status", wrapper.GetWorkerRuntimeStatus)
	router.GET(baseURL+"/workers/:worker_id/settings", wrapper.GetWorkerSettings)
	router.PUT(baseURL+"/workers/:worker_id/settings", wrapper.UpdateWorkerSettings)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdbW/cOJL+K4RugUtybbczM1lgDNwHjzOzY2x8Y8QJcrjE12BL1d3cSKSGpGz3BP7v",
	"C75JlESp1S+xHac/xWlRZLFYT1WxWCx9iWKW5YwClSI6/hKJeAEZ1n+exJIw+hZEzqgA9UvOWQ5cEtDP",
	"MxACz/WDBETMSa7aR8f2RcRBFKlErtkoksscouNISE7oPLobRZJkICTO8s4+qhajaMZ4hmV0HCVYwoF6",
	"EurzhvHPwCckaff5QT9CZ6+RXGCJbrBAOJaQoCJntN3X3Sji8GdBOCTR8ceomkc1hD+Fq7IDNv0XxFIR",
	"c8rojMy7WRjr5+qvv3GYRcfRf4yr5RjbtRgbuk1fK9jmhlqbcY3JWsJ65zeKbg/m7MD+qP4Rh40Je00O",
	"SJYzLjUPsFxExxEuJJOAszGhEjjF6Vj3oWk5ZVRyll6kmMLvgFO52EQOk4SoP3GKFroPRKjhBQmt9ygS",
	"EstCtDv64xo4TlMUG6pQrshyfdqXRhHQIlO8M78vo1GUwJzjBJScFNT9fLUeEMzsUbyA+PPGcBATM7rq",
	"HpdcuaixsU1+RbP6mwOOF3iaQnAGQaINaxCbIfUuMkJVcEiQIStqQaYhhiVv/Yk3phTEHQcsweDmLfxZ",
	"gJBtuQGqZmP1xAwXqYyOJS+gOZkPC5AL4EguwNKNiEDu7XL0KWMpYKqGpziDTvWjHqJnWSEkmgIqKPmz",
	"gOfRKMrw7Rugc7VIP7x6NYoyQt3/XwYYnnOW5bJrlAORQ0xmJEa2XUjaQUpC52KY+rm0rc9oXrQXSs+4",
	"JCq0JL9yznifJkwCLNMvIf0sMAFQT7te2szsmHe3VJ6GrrV1Z51DG6vO31J2c0ZnrFPgJ0JCHtBy/1Nk",
	"U+AarabhGMeSXAMy7cspqDHnwPUK3EJcqNcnMStoQBrfMYlTRMueZym7QeVb4U5TLOSkbBPo07FVdaga",
	"N3odrBtFEccgxIRjGZC9S/MUqadh0stRZinDHsTMdLWkqel38bvJG90MEaoVjRotwJ2GpPn9jxrrO0jm",
	"SmHZSty6Ya2nsUK/lDTcj2vjOLseOGvT3IpZlxLyMD4N3AIq3TNAam2V+YkLzoHKdOlEks6DpgjzeUD0",
	"TuZAZWUjMJ8Xmd4BjCIiIdNvtNWm+QFzjpfG5OdAE6DxcpKzlMTL9jgX+nc0YxwtME1SQueoeg3NMEkL",
	"Dr7zpH6azLBQq4DTdGIxav+npCcFqVYA02X5MOyQqGHEJKRB3hAhHeK0PRZILogw/7cvIq1IhnOj5k2s",
	"Wr0+5wHodZ+btsLz+pVeE86oWk10jTlR4wi9AG78KGCcV+rxyjZo3HjsWmCBpgDUyqE/KU+nE+01tLrV",
	"zoR1UTqIrCZq7EKfzZ9xlhmL4BuDjo7WMTDr2xY9BitkcNp/6N/XIpeD5MuJHm0Avbo1wlKC8f2G0Rx2",
	"W99rD7XCSvBNuF2DRNUaKe2fFCkkhtjBRK7gqeSYinKThxQDUiyDPZlxVxint6pRtfU2c3SMbRFxarRy",
	"nf/o2RH6bzQjXCjyls+DABGfST65WUBAHC8/k1ztnYw+6J2S82hWotg2nBXpKm/MuBhqQlYBhZyY2nwF",
	"yrDvsPud6V+C1gjpZ6uMty+Ag+12aXF3YLet7DUM997I3peRvX/buAvTtblmfVh1txut9HVR78Hzj5JZ",
	"94bPWEeakgkOrJEiCekGm4Wy99h/cOwnHav6/v3Za38di4IkoSV8YOXBEwg5y87iI90A3RC5ILQVk/Xs",
	"9vephUZRkSf96Nbetmn1Vc6qhslZQ13qJv4hlS8fTipqqqs20z4NK7pDPWWUq4T0qqBP6ZcF0P41AkHW",
	"mR0YpeyKeraOKGwz3fVGcaU6Yzd2Us2hy+kC4s9rHJLVzpd6guZdZ2O1982Rr2dtcqxNizI6ASMSPu0Z",
	"xDd/sltyrFuksVIOw45HnBxrPog+Q9XXlz+rlgk7owm5JklRHWf6TBch+7XqQHP1EebDnFsOOQY0i7OG",
	"sGyPsDds/htJQ2FukkLYTL9hc6SedtrojCVkRkKBwzfKtrjHGyg7ztLuU0j1EGEhWEyU3tc+AErZ3BOC",
	"mKUpxFIfZZkggf5zymqHrp6GIH8FxlMMQ+oRIhRNlxJqJyeEyr//tFrJlvy1o3hsGyQAbuG2Wfke05ey",
	"+XDL52h5bEYvtZI6wObp+W5s8mq83HhFzk8vLoFfl3kxAzd9pyzLME023e2Zt7u7lQzxwpzgnZ9eIKEp",
	"DJ5d7343szKbwlEfcvDOQXISi74sG91gmDW0vd3TiZ4jbW1JbE56Y2H0NywB2TBpL2ZzpHZ7Jlw6hQW+",
	"Jlqn1lk9xfFnNpvVElOiGbnVZyv1vn8xTZGQHEuYL73uE0jxsrbztz3ArVk0osGbEgqYd+zwU7ysUXHU",
	"9kmI6scMhqYgbwAostFipfEFqN2ZMPktJFOU/Hh0pLNbzP+OQvvNDN+6ILuoEfCyScC56dXTY/VYtD/w",
	"S3/cl13jtmetCQ4Pu9a8/360goC7ADAvte+zUx81C+bauLML1Tm2aXOZybxxEtRt+jv8zFCfLWeTJNoy",
	"84JSc4ptzvjW9DcNnzYwj0UePrKyjpJ5jBKL3+G+quXdhi5rY9k31kzv9b5+nUy4ferb6tS3Fkp9Nrvm",
	"nexWdpjRSdc0TvVjFx0UC8whQTjmTAikNm2NwISvr6dFwP78qpcL6acO0e2Fc5k6De+9jISU2ZsOBmuG",
	"eTTr2h4VoULiNJ0kwRSpUv4Ysg2r6DbxPR5vIm3bEVLcjRNLZTZnmKSQVLpqXdsR5xPj7228/W/6tC2/",
	"75wlkKJTRiXcSnTBmWQxS62bWV+hYDwgA4m7iQslv56DxAmWGGmnuUqobkpDO/QA/JrEsN5ol+aleu+I",
	"5Z0TEilAPimVc9sqqOel8i4NdSOXb6DBDroqSvFOwlrvHeDM6DwT4ieiFWP3jEhrbrW0//bMsHK9/ipz",
	"qVsrMlTFm7ftc5eyjQWypAX0jOLe6iTSWVt1dCQHrbQZwV3tTvjedSxgB+86F1AgD8qbfc89X73OIdtf",
	"W/iNLb/p5TVITFLRNkL9F2R0alIHxhuZSbELOAeiV4vtLi90uZUfSomnEEtyTeSy7VZW9xXqtxfU/z5T",
	"dkODHmbB087xTi7O0Pu3b/pOcmxe51BfPHRwoygYdcbCmwvbvTH4OsEkC6RBc3Sy15xmBcbey1Meo9q7",
	"nmtMUr2cXYtlW5C0JhwbOKyPQml0ZUNUvV4N1yzb5ULVIzyBlZlXuZUd2YAn18DxHBpmGPXmUmIL9CHp",
	"j2XbbfeA5nR4yBZwKO/Py1jVVuzvuUjTk5Di9ObmKSk73Clufeq9IXYfavdok5NWZBVY4rfJKwgZlfr9",
	"rGod18sCCG2H97vb/e52v7vd72432902lOO9KZPetE1L03apm49WWVV2qKWtkh5mDM94fNQqb6/Znqxm",
	"+1raa0UaqAPIt5EK2mC8z6NtfMGetNAtneV7yB8oSRwWkbj3mMvABJ5WeY0wKNyzoflKjQ1ny24EgzsD",
	"04PutMKJC07k8lKNZ9h4kpN/wvKkMAVLGqmLudVkJxdn6DOYjAdcyAVQSeLSIqqmC8Am09mogOh/D04u",
	"zg7+CcuKL1iPFN3dactlIk0xoxLHGur2xZNCMqUwbHTuOFpImYvj8XhO5KKYHsYsGy9ZwQ8Yn4/V5v1A",
	"oSpQFuXduwtNt6I5wxTPCZ1rDZ0xSiRTC46yIpUkTwG5Ud1qHn6in+g7palUFzln1yQBgaZMLtDp2/ev",
	"PUOnB7DbcD0O6FQhNRIvqI5meCPGODeBMgJmkBcvdH+/0iRnhErx4gV6NrZUjF88P0bnus/gyYNAQjIl",
	"g7aQgTJCUyzgUNEOAhC4XhHmgHB6g5cClfE8TaPqFxHqPAOZLpV8V6NJTChwG9WzFL+18+ogemznbcg3",
	"c0cpuYZWt0KTkHN2u/xEuTnDFTaxiyp23ZTRYHGImnOyUEC2dEawc9WtLDhFr45+QDrZQaCbBdBaMw6I",
	"MukGPfxEda5ODFbvWMk8P3vXEkqWAxWs4DEcKnm0L4mxaqsVqkx9oUa21hLSxZbUtLyo4nH08vDo8Ejf",
	"AcmB4pxEx9GPh0eHP0YjHa3SeB0nLBZj9dccQibyBs/nyoIZwddBLcsfJckJi3UqnsNuKcZnSXQc/QOk",
	"ff+9IoxbPaTH/eHoyAHWJsEo/2q8kFla1TILpNPdtZDpkfj7u/M3KMdzMNqpyDLMl4pfAVIlVobtY6Tm",
	"H12p9uOq0FKQF2/1ygsNjUWzSpL6sV5jSntv8zmHucnSNeJkxwiw6nf3ZAWfcJ6nVluO/yWMB1axq88c",
	"9FTmCvD1tKdi1t0oerVDwurlcwK0nNlgqnO7TZpRfZGD9Mb2loFbbVd4Sq+3hcXhEhuhW7nqf+RAlSy5",
	"QGOVFiitbg8trH3rMod4vdW9PXCUrQGHII0NVoXbBDHhuRy97EnttUFba63hzWgwyAUQXp3ntPj0oXQ/",
	"vhoCml5ggH/u/qOb+GMUdU2j563ZZXO/XN2NopyJUNBF7xIEwojCjVNJ+v6AEm/rlyStnWZ9qfwKbZHx",
	"IEHIX1iy3J2mChSBu6u7q2ove9cSlZc7FpW+lfKPZCDx6jKkOiTz0/1KzTVOSYK4Y5Ya/+f7G9/PEsQp",
	"B5wsEdwSIR+prdBr5oUNWgjydN/4S7kLvzOQ0tesW+B6rX9X4LLAUkpPSJYLRCQiM1SlydYBZV4sAZVj",
	"jjOQWut+7MzzcDslfe5Y7pP8eEEdK6MeI3LVwtFPnbEMM/uQuP90/+LGJJqxgiaPUsjMsvYJ2ajfpiYm",
	"CQPhKSskwqW5rrrssKGPRIiO7l8ZJy5vZS+QbYH8BzivoeRTh/MQKhhg8qSVK2c0u7ef7vcX/ATrh5PM",
	"3Tspofz8QU7KA+DCRoQfoZPywCDde0nd+sII+AZekq4+y6gYJ5CnTCMuvB95rZ+3TVsVTgs4S+qVJ2rn",
	"GnX7++yc4sJDA/oXXIIZPYPD+eGoXD9MFcymUFL6fG+Tw06iRkALYxZBAzCW48KeZwUhdqEer4Uw/cb3",
	"DjDN1f0uZ7UAG/naQn45CIltDm1Qgt+aBmvJsH3ne5diy9u9IA8QZCdmW4iykCzvluNLyfK1hFi98L1L",
	"sGJpvpffAfKrxWsL4S3oCk/ivWmwlgjbd753Kba83YvxgE2nlbINJNnmiaw8q3R5NN4npcoYq5VofYlS",
	"LgBxmBNhipx3BFtt9soTjbk27yr2+Bptru4lfEUY1ufZWgEWlxJVfYUuKPEXnN0ukWR2vP90+edl1hN6",
	"ZoVNlDlSpTJ/vlLmy3vOT0vyG1/C6zn6rcW9H4ew/3DvBHg3tNGzKsXPS4F73kBAQ2O0EtstDJw+Xw0D",
	"d+1iIAhMLvpOIPCb+STR0wJA7YtJ3QvfuAMsJJawR8GmKAhyc1MwjMsaH+tAwlxRKoGhE4Mqitxx9NZ4",
	"ubRXu54eaOrloFcgx3A7zOQ9jLaCUXl5cG3wrMgBbgPHJpruxpqUOcBPCxqrk40/+NnRXpbxfvfAv1kk",
	"dqRgD8eiq808EImq+Y5w+MZUSb5/FI4CNbglcDO36dLU/n5WlvceIVfde6QvEz13tPxZgI5ZWGJ0PXF/",
	"3M0KhbfJa9dwLWtR63s3OuLSQVRKMiJrVJVlW18d1SocrKq9+jV1V63kdTdatKzujfaGqsJVJd9IRYy/",
	"uBrzd+tpC1Pdf2caw5apfwRKw325wN4NDgzkPe0eJ8dS2aPoOPr/j/jgr5OD/zs6+HlyeHD1X58+HaZs",
	"/rdogIaoqgrqW9YpoQNUg/KBa5rBVwY7UAf6rlmeYkLXvF1TfhPCdfZAkGe8EuAnAX89lY1UgFfdfiD0",
	"7Rs7Qn5VFuxpOe3NCvvd659VnwzYm79N5N/7CsLa4l8V2hwo/fbO6m6E/9Ld5ntast8o4d6XnvCIdqrf",
	"oORX1T0HC75flWTA9RlIkHvD1JsYfo3msiou8hSPdlsFYHrE3HFiH5LpP9D169Gse7FmTTENfbfgqV6v",
	"aX6X4UGu2WyAl/29m28n78i/7NKPY7/0kQaZX/To49Xd6IvCRFmY7mN7ex6bcm5evYryc2NVQZjj8ThV",
	"LRdMyOOfj34+ilS3lpwOZDeLCekryE4Yq3JCTcgrxf5lSP0PUw6+rJlT9WPPTdrduOI+VZ0ducCyLLbT",
	"qMxTldHxgpfWJWj37WJvZAbxMk5N6R5GQ/S57LG7q7t/BwAA//8MlvvWOJMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
